# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import goods_pb2 as goods__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class GoodsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBannerList = channel.unary_unary(
                '/Goods/GetBannerList',
                request_serializer=goods__pb2.BannerFilterRequest.SerializeToString,
                response_deserializer=goods__pb2.BannerListResponse.FromString,
                )
        self.CreateBanner = channel.unary_unary(
                '/Goods/CreateBanner',
                request_serializer=goods__pb2.BannerRequest.SerializeToString,
                response_deserializer=goods__pb2.BannerInfoResponse.FromString,
                )
        self.UpdateBanner = channel.unary_unary(
                '/Goods/UpdateBanner',
                request_serializer=goods__pb2.BannerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteBanner = channel.unary_unary(
                '/Goods/DeleteBanner',
                request_serializer=goods__pb2.BannerByIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CategoryList = channel.unary_unary(
                '/Goods/CategoryList',
                request_serializer=goods__pb2.CategoryFilterRequest.SerializeToString,
                response_deserializer=goods__pb2.CategoryListResponse.FromString,
                )
        self.CreateCategory = channel.unary_unary(
                '/Goods/CreateCategory',
                request_serializer=goods__pb2.CategoryRequest.SerializeToString,
                response_deserializer=goods__pb2.CategoryInfoResponse.FromString,
                )
        self.DeleteCategory = channel.unary_unary(
                '/Goods/DeleteCategory',
                request_serializer=goods__pb2.CategoryByIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateCategory = channel.unary_unary(
                '/Goods/UpdateCategory',
                request_serializer=goods__pb2.CategoryRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetBrandList = channel.unary_unary(
                '/Goods/GetBrandList',
                request_serializer=goods__pb2.BrandFilterRquest.SerializeToString,
                response_deserializer=goods__pb2.BrandListResponse.FromString,
                )
        self.CreateBrand = channel.unary_unary(
                '/Goods/CreateBrand',
                request_serializer=goods__pb2.CreateBrandRequest.SerializeToString,
                response_deserializer=goods__pb2.BrandInfoResponse.FromString,
                )
        self.DeleteBrand = channel.unary_unary(
                '/Goods/DeleteBrand',
                request_serializer=goods__pb2.BrandByIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateBrand = channel.unary_unary(
                '/Goods/UpdateBrand',
                request_serializer=goods__pb2.BrandInfoRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetBrandsByCategory = channel.unary_unary(
                '/Goods/GetBrandsByCategory',
                request_serializer=goods__pb2.CategoryByIdRequest.SerializeToString,
                response_deserializer=goods__pb2.BrandListResponse.FromString,
                )
        self.CategoryBrandList = channel.unary_unary(
                '/Goods/CategoryBrandList',
                request_serializer=goods__pb2.CategoryBrandFilterRequest.SerializeToString,
                response_deserializer=goods__pb2.CategoryBrandListResponse.FromString,
                )
        self.UpdateCategoryBrand = channel.unary_unary(
                '/Goods/UpdateCategoryBrand',
                request_serializer=goods__pb2.CategoryBrandRequest.SerializeToString,
                response_deserializer=goods__pb2.CategoryBrandResponse.FromString,
                )
        self.CreateCategoryBrand = channel.unary_unary(
                '/Goods/CreateCategoryBrand',
                request_serializer=goods__pb2.CategoryBrandRequest.SerializeToString,
                response_deserializer=goods__pb2.CategoryBrandResponse.FromString,
                )
        self.DeleteCategoryBrand = channel.unary_unary(
                '/Goods/DeleteCategoryBrand',
                request_serializer=goods__pb2.CategoryBrandRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GoodsList = channel.unary_unary(
                '/Goods/GoodsList',
                request_serializer=goods__pb2.GoodsFilterRequest.SerializeToString,
                response_deserializer=goods__pb2.GoodsListResponse.FromString,
                )
        self.BatchGetGoods = channel.unary_unary(
                '/Goods/BatchGetGoods',
                request_serializer=goods__pb2.BatchGoodsByIdRequest.SerializeToString,
                response_deserializer=goods__pb2.GoodsListResponse.FromString,
                )
        self.GetGoodsDetail = channel.unary_unary(
                '/Goods/GetGoodsDetail',
                request_serializer=goods__pb2.GoodsByIdRequest.SerializeToString,
                response_deserializer=goods__pb2.GoodsDetailResponse.FromString,
                )
        self.CreateGoods = channel.unary_unary(
                '/Goods/CreateGoods',
                request_serializer=goods__pb2.GoodsRequest.SerializeToString,
                response_deserializer=goods__pb2.GoodsDetailResponse.FromString,
                )
        self.DeleteGoods = channel.unary_unary(
                '/Goods/DeleteGoods',
                request_serializer=goods__pb2.GoodsByIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateGoods = channel.unary_unary(
                '/Goods/UpdateGoods',
                request_serializer=goods__pb2.GoodsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateStatus = channel.unary_unary(
                '/Goods/UpdateStatus',
                request_serializer=goods__pb2.GoodsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class GoodsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBannerList(self, request, context):
        """banner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBanner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBanner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBanner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CategoryList(self, request, context):
        """分类
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBrandList(self, request, context):
        """品牌
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBrand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBrand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBrand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBrandsByCategory(self, request, context):
        """获取指定 category 下 brand列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CategoryBrandList(self, request, context):
        """获取所有分类品牌 = 类名+品牌名
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategoryBrand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCategoryBrand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategoryBrand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GoodsList(self, request, context):
        """商品
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetGoods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGoodsDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGoods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGoods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGoods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GoodsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBannerList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBannerList,
                    request_deserializer=goods__pb2.BannerFilterRequest.FromString,
                    response_serializer=goods__pb2.BannerListResponse.SerializeToString,
            ),
            'CreateBanner': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBanner,
                    request_deserializer=goods__pb2.BannerRequest.FromString,
                    response_serializer=goods__pb2.BannerInfoResponse.SerializeToString,
            ),
            'UpdateBanner': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBanner,
                    request_deserializer=goods__pb2.BannerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteBanner': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBanner,
                    request_deserializer=goods__pb2.BannerByIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CategoryList': grpc.unary_unary_rpc_method_handler(
                    servicer.CategoryList,
                    request_deserializer=goods__pb2.CategoryFilterRequest.FromString,
                    response_serializer=goods__pb2.CategoryListResponse.SerializeToString,
            ),
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=goods__pb2.CategoryRequest.FromString,
                    response_serializer=goods__pb2.CategoryInfoResponse.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=goods__pb2.CategoryByIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategory,
                    request_deserializer=goods__pb2.CategoryRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBrandList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBrandList,
                    request_deserializer=goods__pb2.BrandFilterRquest.FromString,
                    response_serializer=goods__pb2.BrandListResponse.SerializeToString,
            ),
            'CreateBrand': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBrand,
                    request_deserializer=goods__pb2.CreateBrandRequest.FromString,
                    response_serializer=goods__pb2.BrandInfoResponse.SerializeToString,
            ),
            'DeleteBrand': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBrand,
                    request_deserializer=goods__pb2.BrandByIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateBrand': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBrand,
                    request_deserializer=goods__pb2.BrandInfoRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBrandsByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBrandsByCategory,
                    request_deserializer=goods__pb2.CategoryByIdRequest.FromString,
                    response_serializer=goods__pb2.BrandListResponse.SerializeToString,
            ),
            'CategoryBrandList': grpc.unary_unary_rpc_method_handler(
                    servicer.CategoryBrandList,
                    request_deserializer=goods__pb2.CategoryBrandFilterRequest.FromString,
                    response_serializer=goods__pb2.CategoryBrandListResponse.SerializeToString,
            ),
            'UpdateCategoryBrand': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategoryBrand,
                    request_deserializer=goods__pb2.CategoryBrandRequest.FromString,
                    response_serializer=goods__pb2.CategoryBrandResponse.SerializeToString,
            ),
            'CreateCategoryBrand': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategoryBrand,
                    request_deserializer=goods__pb2.CategoryBrandRequest.FromString,
                    response_serializer=goods__pb2.CategoryBrandResponse.SerializeToString,
            ),
            'DeleteCategoryBrand': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategoryBrand,
                    request_deserializer=goods__pb2.CategoryBrandRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GoodsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GoodsList,
                    request_deserializer=goods__pb2.GoodsFilterRequest.FromString,
                    response_serializer=goods__pb2.GoodsListResponse.SerializeToString,
            ),
            'BatchGetGoods': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetGoods,
                    request_deserializer=goods__pb2.BatchGoodsByIdRequest.FromString,
                    response_serializer=goods__pb2.GoodsListResponse.SerializeToString,
            ),
            'GetGoodsDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGoodsDetail,
                    request_deserializer=goods__pb2.GoodsByIdRequest.FromString,
                    response_serializer=goods__pb2.GoodsDetailResponse.SerializeToString,
            ),
            'CreateGoods': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGoods,
                    request_deserializer=goods__pb2.GoodsRequest.FromString,
                    response_serializer=goods__pb2.GoodsDetailResponse.SerializeToString,
            ),
            'DeleteGoods': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGoods,
                    request_deserializer=goods__pb2.GoodsByIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateGoods': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGoods,
                    request_deserializer=goods__pb2.GoodsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=goods__pb2.GoodsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Goods', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Goods(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBannerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/GetBannerList',
            goods__pb2.BannerFilterRequest.SerializeToString,
            goods__pb2.BannerListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBanner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/CreateBanner',
            goods__pb2.BannerRequest.SerializeToString,
            goods__pb2.BannerInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBanner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/UpdateBanner',
            goods__pb2.BannerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBanner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/DeleteBanner',
            goods__pb2.BannerByIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CategoryList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/CategoryList',
            goods__pb2.CategoryFilterRequest.SerializeToString,
            goods__pb2.CategoryListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/CreateCategory',
            goods__pb2.CategoryRequest.SerializeToString,
            goods__pb2.CategoryInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/DeleteCategory',
            goods__pb2.CategoryByIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/UpdateCategory',
            goods__pb2.CategoryRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBrandList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/GetBrandList',
            goods__pb2.BrandFilterRquest.SerializeToString,
            goods__pb2.BrandListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBrand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/CreateBrand',
            goods__pb2.CreateBrandRequest.SerializeToString,
            goods__pb2.BrandInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBrand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/DeleteBrand',
            goods__pb2.BrandByIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBrand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/UpdateBrand',
            goods__pb2.BrandInfoRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBrandsByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/GetBrandsByCategory',
            goods__pb2.CategoryByIdRequest.SerializeToString,
            goods__pb2.BrandListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CategoryBrandList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/CategoryBrandList',
            goods__pb2.CategoryBrandFilterRequest.SerializeToString,
            goods__pb2.CategoryBrandListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCategoryBrand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/UpdateCategoryBrand',
            goods__pb2.CategoryBrandRequest.SerializeToString,
            goods__pb2.CategoryBrandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCategoryBrand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/CreateCategoryBrand',
            goods__pb2.CategoryBrandRequest.SerializeToString,
            goods__pb2.CategoryBrandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCategoryBrand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/DeleteCategoryBrand',
            goods__pb2.CategoryBrandRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GoodsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/GoodsList',
            goods__pb2.GoodsFilterRequest.SerializeToString,
            goods__pb2.GoodsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchGetGoods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/BatchGetGoods',
            goods__pb2.BatchGoodsByIdRequest.SerializeToString,
            goods__pb2.GoodsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGoodsDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/GetGoodsDetail',
            goods__pb2.GoodsByIdRequest.SerializeToString,
            goods__pb2.GoodsDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateGoods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/CreateGoods',
            goods__pb2.GoodsRequest.SerializeToString,
            goods__pb2.GoodsDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteGoods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/DeleteGoods',
            goods__pb2.GoodsByIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateGoods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/UpdateGoods',
            goods__pb2.GoodsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goods/UpdateStatus',
            goods__pb2.GoodsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
