# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopcart.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shopcart.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eshopcart.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x10GoodsInfoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1d\n\x0fUserInfoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"E\n\x14ShopCartListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x1e\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x10.ShopCartRequest\"S\n\x0fShopCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08goods_id\x18\x02 \x01(\x05\x12\x0c\n\x04nums\x18\x03 \x01(\x05\x12\x0f\n\x07\x63hecked\x18\x04 \x01(\x08\x32\x80\x02\n\x08ShopCart\x12>\n\x12\x41\x64\x64GoodsToShopCart\x12\x10.ShopCartRequest\x1a\x16.google.protobuf.Empty\x12\x38\n\rQueryShopCart\x12\x10.UserInfoRequest\x1a\x15.ShopCartListResponse\x12:\n\x0eUpdateShopCart\x12\x10.ShopCartRequest\x1a\x16.google.protobuf.Empty\x12>\n\x12\x44\x65lGoodsInShopCart\x12\x10.ShopCartRequest\x1a\x16.google.protobuf.EmptyB\tZ\x07.;protob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_GOODSINFOREQUEST = _descriptor.Descriptor(
  name='GoodsInfoRequest',
  full_name='GoodsInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GoodsInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=77,
)


_USERINFOREQUEST = _descriptor.Descriptor(
  name='UserInfoRequest',
  full_name='UserInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=108,
)


_SHOPCARTLISTRESPONSE = _descriptor.Descriptor(
  name='ShopCartListResponse',
  full_name='ShopCartListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='ShopCartListResponse.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ShopCartListResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=179,
)


_SHOPCARTREQUEST = _descriptor.Descriptor(
  name='ShopCartRequest',
  full_name='ShopCartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ShopCartRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goods_id', full_name='ShopCartRequest.goods_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nums', full_name='ShopCartRequest.nums', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='checked', full_name='ShopCartRequest.checked', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=264,
)

_SHOPCARTLISTRESPONSE.fields_by_name['data'].message_type = _SHOPCARTREQUEST
DESCRIPTOR.message_types_by_name['GoodsInfoRequest'] = _GOODSINFOREQUEST
DESCRIPTOR.message_types_by_name['UserInfoRequest'] = _USERINFOREQUEST
DESCRIPTOR.message_types_by_name['ShopCartListResponse'] = _SHOPCARTLISTRESPONSE
DESCRIPTOR.message_types_by_name['ShopCartRequest'] = _SHOPCARTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GoodsInfoRequest = _reflection.GeneratedProtocolMessageType('GoodsInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _GOODSINFOREQUEST,
  '__module__' : 'shopcart_pb2'
  # @@protoc_insertion_point(class_scope:GoodsInfoRequest)
  })
_sym_db.RegisterMessage(GoodsInfoRequest)

UserInfoRequest = _reflection.GeneratedProtocolMessageType('UserInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERINFOREQUEST,
  '__module__' : 'shopcart_pb2'
  # @@protoc_insertion_point(class_scope:UserInfoRequest)
  })
_sym_db.RegisterMessage(UserInfoRequest)

ShopCartListResponse = _reflection.GeneratedProtocolMessageType('ShopCartListResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOPCARTLISTRESPONSE,
  '__module__' : 'shopcart_pb2'
  # @@protoc_insertion_point(class_scope:ShopCartListResponse)
  })
_sym_db.RegisterMessage(ShopCartListResponse)

ShopCartRequest = _reflection.GeneratedProtocolMessageType('ShopCartRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOPCARTREQUEST,
  '__module__' : 'shopcart_pb2'
  # @@protoc_insertion_point(class_scope:ShopCartRequest)
  })
_sym_db.RegisterMessage(ShopCartRequest)


DESCRIPTOR._options = None

_SHOPCART = _descriptor.ServiceDescriptor(
  name='ShopCart',
  full_name='ShopCart',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=267,
  serialized_end=523,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddGoodsToShopCart',
    full_name='ShopCart.AddGoodsToShopCart',
    index=0,
    containing_service=None,
    input_type=_SHOPCARTREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryShopCart',
    full_name='ShopCart.QueryShopCart',
    index=1,
    containing_service=None,
    input_type=_USERINFOREQUEST,
    output_type=_SHOPCARTLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateShopCart',
    full_name='ShopCart.UpdateShopCart',
    index=2,
    containing_service=None,
    input_type=_SHOPCARTREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DelGoodsInShopCart',
    full_name='ShopCart.DelGoodsInShopCart',
    index=3,
    containing_service=None,
    input_type=_SHOPCARTREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOPCART)

DESCRIPTOR.services_by_name['ShopCart'] = _SHOPCART

# @@protoc_insertion_point(module_scope)
