# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import shopcart_pb2 as shopcart__pb2


class ShopCartStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddGoodsToShopCart = channel.unary_unary(
                '/ShopCart/AddGoodsToShopCart',
                request_serializer=shopcart__pb2.ShopCartRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.QueryShopCart = channel.unary_unary(
                '/ShopCart/QueryShopCart',
                request_serializer=shopcart__pb2.UserInfoRequest.SerializeToString,
                response_deserializer=shopcart__pb2.ShopCartListResponse.FromString,
                )
        self.UpdateShopCart = channel.unary_unary(
                '/ShopCart/UpdateShopCart',
                request_serializer=shopcart__pb2.ShopCartRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DelGoodsInShopCart = channel.unary_unary(
                '/ShopCart/DelGoodsInShopCart',
                request_serializer=shopcart__pb2.ShopCartRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ShopCartServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddGoodsToShopCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryShopCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateShopCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelGoodsInShopCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopCartServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddGoodsToShopCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGoodsToShopCart,
                    request_deserializer=shopcart__pb2.ShopCartRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'QueryShopCart': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryShopCart,
                    request_deserializer=shopcart__pb2.UserInfoRequest.FromString,
                    response_serializer=shopcart__pb2.ShopCartListResponse.SerializeToString,
            ),
            'UpdateShopCart': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateShopCart,
                    request_deserializer=shopcart__pb2.ShopCartRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DelGoodsInShopCart': grpc.unary_unary_rpc_method_handler(
                    servicer.DelGoodsInShopCart,
                    request_deserializer=shopcart__pb2.ShopCartRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ShopCart', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShopCart(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddGoodsToShopCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShopCart/AddGoodsToShopCart',
            shopcart__pb2.ShopCartRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryShopCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShopCart/QueryShopCart',
            shopcart__pb2.UserInfoRequest.SerializeToString,
            shopcart__pb2.ShopCartListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateShopCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShopCart/UpdateShopCart',
            shopcart__pb2.ShopCartRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelGoodsInShopCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShopCart/DelGoodsInShopCart',
            shopcart__pb2.ShopCartRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
