// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: shopcart.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GoodsInfoRequest) Reset() {
	*x = GoodsInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopcart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoRequest) ProtoMessage() {}

func (x *GoodsInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopcart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoRequest.ProtoReflect.Descriptor instead.
func (*GoodsInfoRequest) Descriptor() ([]byte, []int) {
	return file_shopcart_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserInfoRequest) Reset() {
	*x = UserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopcart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequest) ProtoMessage() {}

func (x *UserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopcart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequest.ProtoReflect.Descriptor instead.
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return file_shopcart_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ShopCartListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*ShopCartRequest `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ShopCartListResponse) Reset() {
	*x = ShopCartListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopcart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopCartListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartListResponse) ProtoMessage() {}

func (x *ShopCartListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopcart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartListResponse.ProtoReflect.Descriptor instead.
func (*ShopCartListResponse) Descriptor() ([]byte, []int) {
	return file_shopcart_proto_rawDescGZIP(), []int{2}
}

func (x *ShopCartListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ShopCartListResponse) GetData() []*ShopCartRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShopCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId int32 `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Nums    int32 `protobuf:"varint,3,opt,name=nums,proto3" json:"nums,omitempty"`
	Checked bool  `protobuf:"varint,4,opt,name=checked,proto3" json:"checked,omitempty"`
}

func (x *ShopCartRequest) Reset() {
	*x = ShopCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopcart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartRequest) ProtoMessage() {}

func (x *ShopCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopcart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartRequest.ProtoReflect.Descriptor instead.
func (*ShopCartRequest) Descriptor() ([]byte, []int) {
	return file_shopcart_proto_rawDescGZIP(), []int{3}
}

func (x *ShopCartRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShopCartRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *ShopCartRequest) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *ShopCartRequest) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

var File_shopcart_proto protoreflect.FileDescriptor

var file_shopcart_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a,
	0x10, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x21, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x14, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x71, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x32, 0x80, 0x02, 0x0a, 0x08,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x12, 0x3e, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x54, 0x6f, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x12, 0x10, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x68,
	0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x61, 0x72, 0x74, 0x12, 0x10, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3e,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x61, 0x72, 0x74, 0x12, 0x10, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_shopcart_proto_rawDescOnce sync.Once
	file_shopcart_proto_rawDescData = file_shopcart_proto_rawDesc
)

func file_shopcart_proto_rawDescGZIP() []byte {
	file_shopcart_proto_rawDescOnce.Do(func() {
		file_shopcart_proto_rawDescData = protoimpl.X.CompressGZIP(file_shopcart_proto_rawDescData)
	})
	return file_shopcart_proto_rawDescData
}

var file_shopcart_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shopcart_proto_goTypes = []interface{}{
	(*GoodsInfoRequest)(nil),     // 0: GoodsInfoRequest
	(*UserInfoRequest)(nil),      // 1: UserInfoRequest
	(*ShopCartListResponse)(nil), // 2: ShopCartListResponse
	(*ShopCartRequest)(nil),      // 3: ShopCartRequest
	(*emptypb.Empty)(nil),        // 4: google.protobuf.Empty
}
var file_shopcart_proto_depIdxs = []int32{
	3, // 0: ShopCartListResponse.data:type_name -> ShopCartRequest
	3, // 1: ShopCart.AddGoodsToShopCart:input_type -> ShopCartRequest
	1, // 2: ShopCart.QueryShopCart:input_type -> UserInfoRequest
	3, // 3: ShopCart.UpdateShopCart:input_type -> ShopCartRequest
	3, // 4: ShopCart.DelGoodsInShopCart:input_type -> ShopCartRequest
	4, // 5: ShopCart.AddGoodsToShopCart:output_type -> google.protobuf.Empty
	2, // 6: ShopCart.QueryShopCart:output_type -> ShopCartListResponse
	4, // 7: ShopCart.UpdateShopCart:output_type -> google.protobuf.Empty
	4, // 8: ShopCart.DelGoodsInShopCart:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shopcart_proto_init() }
func file_shopcart_proto_init() {
	if File_shopcart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shopcart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopcart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopcart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopCartListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopcart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shopcart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopcart_proto_goTypes,
		DependencyIndexes: file_shopcart_proto_depIdxs,
		MessageInfos:      file_shopcart_proto_msgTypes,
	}.Build()
	File_shopcart_proto = out.File
	file_shopcart_proto_rawDesc = nil
	file_shopcart_proto_goTypes = nil
	file_shopcart_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShopCartClient is the client API for ShopCart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopCartClient interface {
	AddGoodsToShopCart(ctx context.Context, in *ShopCartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	QueryShopCart(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*ShopCartListResponse, error)
	UpdateShopCart(ctx context.Context, in *ShopCartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DelGoodsInShopCart(ctx context.Context, in *ShopCartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type shopCartClient struct {
	cc grpc.ClientConnInterface
}

func NewShopCartClient(cc grpc.ClientConnInterface) ShopCartClient {
	return &shopCartClient{cc}
}

func (c *shopCartClient) AddGoodsToShopCart(ctx context.Context, in *ShopCartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ShopCart/AddGoodsToShopCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCartClient) QueryShopCart(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*ShopCartListResponse, error) {
	out := new(ShopCartListResponse)
	err := c.cc.Invoke(ctx, "/ShopCart/QueryShopCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCartClient) UpdateShopCart(ctx context.Context, in *ShopCartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ShopCart/UpdateShopCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCartClient) DelGoodsInShopCart(ctx context.Context, in *ShopCartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ShopCart/DelGoodsInShopCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopCartServer is the server API for ShopCart service.
type ShopCartServer interface {
	AddGoodsToShopCart(context.Context, *ShopCartRequest) (*emptypb.Empty, error)
	QueryShopCart(context.Context, *UserInfoRequest) (*ShopCartListResponse, error)
	UpdateShopCart(context.Context, *ShopCartRequest) (*emptypb.Empty, error)
	DelGoodsInShopCart(context.Context, *ShopCartRequest) (*emptypb.Empty, error)
}

// UnimplementedShopCartServer can be embedded to have forward compatible implementations.
type UnimplementedShopCartServer struct {
}

func (*UnimplementedShopCartServer) AddGoodsToShopCart(context.Context, *ShopCartRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGoodsToShopCart not implemented")
}
func (*UnimplementedShopCartServer) QueryShopCart(context.Context, *UserInfoRequest) (*ShopCartListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryShopCart not implemented")
}
func (*UnimplementedShopCartServer) UpdateShopCart(context.Context, *ShopCartRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShopCart not implemented")
}
func (*UnimplementedShopCartServer) DelGoodsInShopCart(context.Context, *ShopCartRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelGoodsInShopCart not implemented")
}

func RegisterShopCartServer(s *grpc.Server, srv ShopCartServer) {
	s.RegisterService(&_ShopCart_serviceDesc, srv)
}

func _ShopCart_AddGoodsToShopCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCartServer).AddGoodsToShopCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopCart/AddGoodsToShopCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCartServer).AddGoodsToShopCart(ctx, req.(*ShopCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopCart_QueryShopCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCartServer).QueryShopCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopCart/QueryShopCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCartServer).QueryShopCart(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopCart_UpdateShopCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCartServer).UpdateShopCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopCart/UpdateShopCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCartServer).UpdateShopCart(ctx, req.(*ShopCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopCart_DelGoodsInShopCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCartServer).DelGoodsInShopCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopCart/DelGoodsInShopCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCartServer).DelGoodsInShopCart(ctx, req.(*ShopCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopCart_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShopCart",
	HandlerType: (*ShopCartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGoodsToShopCart",
			Handler:    _ShopCart_AddGoodsToShopCart_Handler,
		},
		{
			MethodName: "QueryShopCart",
			Handler:    _ShopCart_QueryShopCart_Handler,
		},
		{
			MethodName: "UpdateShopCart",
			Handler:    _ShopCart_UpdateShopCart_Handler,
		},
		{
			MethodName: "DelGoodsInShopCart",
			Handler:    _ShopCart_DelGoodsInShopCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shopcart.proto",
}
