# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: favorites.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='favorites.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66\x61vorites.proto\x1a\x1bgoogle/protobuf/empty.proto\"3\n\x0eUserFavRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08goods_id\x18\x02 \x01(\x05\"t\n\x0b\x46\x61vResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08goods_id\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x12\n\nshop_price\x18\x04 \x01(\x02\x12\x0e\n\x06stocks\x18\x05 \x01(\x05\x12\x0f\n\x07on_sale\x18\x06 \x01(\x08\"<\n\x0f\x46\x61vListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x1a\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x0c.FavResponse\"$\n\x11\x46\x61vStatusResponse\x12\x0f\n\x07\x63hecked\x18\x01 \x01(\x08\x32\xd2\x01\n\tFavorites\x12)\n\x08QueryFav\x12\x0f.UserFavRequest\x1a\x0c.FavResponse\x12\x31\n\x0cQueryFavList\x12\x0f.UserFavRequest\x1a\x10.FavListResponse\x12\x31\n\x06\x41\x64\x64\x46\x61v\x12\x0f.UserFavRequest\x1a\x16.google.protobuf.Empty\x12\x34\n\tDeleteFav\x12\x0f.UserFavRequest\x1a\x16.google.protobuf.EmptyB\tZ\x07.;protob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_USERFAVREQUEST = _descriptor.Descriptor(
  name='UserFavRequest',
  full_name='UserFavRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserFavRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goods_id', full_name='UserFavRequest.goods_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=99,
)


_FAVRESPONSE = _descriptor.Descriptor(
  name='FavResponse',
  full_name='FavResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='FavResponse.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goods_id', full_name='FavResponse.goods_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='FavResponse.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shop_price', full_name='FavResponse.shop_price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stocks', full_name='FavResponse.stocks', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='on_sale', full_name='FavResponse.on_sale', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=217,
)


_FAVLISTRESPONSE = _descriptor.Descriptor(
  name='FavListResponse',
  full_name='FavListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='FavListResponse.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='FavListResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=279,
)


_FAVSTATUSRESPONSE = _descriptor.Descriptor(
  name='FavStatusResponse',
  full_name='FavStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='checked', full_name='FavStatusResponse.checked', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=317,
)

_FAVLISTRESPONSE.fields_by_name['data'].message_type = _FAVRESPONSE
DESCRIPTOR.message_types_by_name['UserFavRequest'] = _USERFAVREQUEST
DESCRIPTOR.message_types_by_name['FavResponse'] = _FAVRESPONSE
DESCRIPTOR.message_types_by_name['FavListResponse'] = _FAVLISTRESPONSE
DESCRIPTOR.message_types_by_name['FavStatusResponse'] = _FAVSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserFavRequest = _reflection.GeneratedProtocolMessageType('UserFavRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERFAVREQUEST,
  '__module__' : 'favorites_pb2'
  # @@protoc_insertion_point(class_scope:UserFavRequest)
  })
_sym_db.RegisterMessage(UserFavRequest)

FavResponse = _reflection.GeneratedProtocolMessageType('FavResponse', (_message.Message,), {
  'DESCRIPTOR' : _FAVRESPONSE,
  '__module__' : 'favorites_pb2'
  # @@protoc_insertion_point(class_scope:FavResponse)
  })
_sym_db.RegisterMessage(FavResponse)

FavListResponse = _reflection.GeneratedProtocolMessageType('FavListResponse', (_message.Message,), {
  'DESCRIPTOR' : _FAVLISTRESPONSE,
  '__module__' : 'favorites_pb2'
  # @@protoc_insertion_point(class_scope:FavListResponse)
  })
_sym_db.RegisterMessage(FavListResponse)

FavStatusResponse = _reflection.GeneratedProtocolMessageType('FavStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _FAVSTATUSRESPONSE,
  '__module__' : 'favorites_pb2'
  # @@protoc_insertion_point(class_scope:FavStatusResponse)
  })
_sym_db.RegisterMessage(FavStatusResponse)


DESCRIPTOR._options = None

_FAVORITES = _descriptor.ServiceDescriptor(
  name='Favorites',
  full_name='Favorites',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=320,
  serialized_end=530,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryFav',
    full_name='Favorites.QueryFav',
    index=0,
    containing_service=None,
    input_type=_USERFAVREQUEST,
    output_type=_FAVRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryFavList',
    full_name='Favorites.QueryFavList',
    index=1,
    containing_service=None,
    input_type=_USERFAVREQUEST,
    output_type=_FAVLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddFav',
    full_name='Favorites.AddFav',
    index=2,
    containing_service=None,
    input_type=_USERFAVREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteFav',
    full_name='Favorites.DeleteFav',
    index=3,
    containing_service=None,
    input_type=_USERFAVREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAVORITES)

DESCRIPTOR.services_by_name['Favorites'] = _FAVORITES

# @@protoc_insertion_point(module_scope)
