# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import favorites_pb2 as favorites__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FavoritesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryFav = channel.unary_unary(
                '/Favorites/QueryFav',
                request_serializer=favorites__pb2.UserFavRequest.SerializeToString,
                response_deserializer=favorites__pb2.FavResponse.FromString,
                )
        self.QueryFavList = channel.unary_unary(
                '/Favorites/QueryFavList',
                request_serializer=favorites__pb2.UserFavRequest.SerializeToString,
                response_deserializer=favorites__pb2.FavListResponse.FromString,
                )
        self.AddFav = channel.unary_unary(
                '/Favorites/AddFav',
                request_serializer=favorites__pb2.UserFavRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteFav = channel.unary_unary(
                '/Favorites/DeleteFav',
                request_serializer=favorites__pb2.UserFavRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class FavoritesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryFav(self, request, context):
        """收藏
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryFavList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FavoritesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryFav': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryFav,
                    request_deserializer=favorites__pb2.UserFavRequest.FromString,
                    response_serializer=favorites__pb2.FavResponse.SerializeToString,
            ),
            'QueryFavList': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryFavList,
                    request_deserializer=favorites__pb2.UserFavRequest.FromString,
                    response_serializer=favorites__pb2.FavListResponse.SerializeToString,
            ),
            'AddFav': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFav,
                    request_deserializer=favorites__pb2.UserFavRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteFav': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFav,
                    request_deserializer=favorites__pb2.UserFavRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Favorites', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Favorites(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryFav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favorites/QueryFav',
            favorites__pb2.UserFavRequest.SerializeToString,
            favorites__pb2.FavResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryFavList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favorites/QueryFavList',
            favorites__pb2.UserFavRequest.SerializeToString,
            favorites__pb2.FavListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favorites/AddFav',
            favorites__pb2.UserFavRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favorites/DeleteFav',
            favorites__pb2.UserFavRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
